### ISSUE TITLE
Great job! In commaqa, what model is the QS sub-question generated by, only gpt3 is used?

### ISSUE THREAD

**Issue by TccccD** [allenai/DecomP#1]
In commaqa, i have two questions：
1. What model is the QS sub-question generated by, only gpt3 is used?
2. Generate multiple questions at once, or step by step (generate a question, then find and merge answers, and then generate a second question)

@dirkgr @schmmd @iellenberger @MLatzke @pdasigi

**Comment by tusharkhot** [comment]
Thanks for the questions. I am just seeing this. 
1. All questions are generated by GPT3
2. We generate questions step by step using the entire history of sub-questions and answers.
